### ISSUE TITLE
fix: 'sync' endpoint does not work

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp-dre-node#15]
e.g. https://dre-1.warp.cc/sync?id=KT45jaf8n9UwgkEareWxPgLJk4oMWpI5NODgYVIF1fY
`readGwPubSubConfig is not a function`

..probably after recent changes in env/configuration options handling.

1. Fix the `scheduleSync.js` endpoint implementation
2. update the readme and add info about the `sync` endpoint in the https://github.com/warp-contracts/warp-dre-node#5-endpoints section

**Comment by koonopek** [comment]
So I have pick up this issue, cause I wanted to get better understanding of DRE codebase.

As far as I understand we resigned from using configuration files, and switched to env variables with `dotenv`.
The fix is pretty easy, however to test functionality, I need this configuration:
```
GW_PORT=''
GW_HOST=''
GW_USERNAME=default
GW_PASSWORD=''
GW_TLS=true
GW_ENABLE_OFFLINE_QUEUE=true
GW_LAZY_CONNECT=true
```

**Comment by koonopek** [comment]
Thanks @asiaziola !

**Comment by koonopek** [comment]
Waiting for merge #18

**Comment by Max-Levitskiy** [comment]
@ppedziwiatr more or less I have a solution. But not sure yet about the trust to the certificate. Need to solve this issue and we'll be able to enable TLS.
